### ISSUE TITLE
9.Владислав Лукьянов

### ISSUE THREAD

**Issue by VladislavLukyanov** [MIEE-ACS/domashnee-zadanie-no3-VladislavLukyanov#1]
Проверьте дз 9 вариант

**Comment by d-makarenko** [comment]
Вычисляется неверно. 
Я бы считал следующим способом: 

    1. Если текущий символ - буква, то ставим флажок - предложение началось
    2. Если текущий символ - знак препинания, то 
        а. если стоит флажок "предложение началось" - инкрементируем счетчик предложений
        б. сбрасываем этот флажок в 0
    3. повторяем 1 и 2 до конца строки

2/4
